export const BUDGET_MAX_ITEMS = 12;
export const BUDGET_ITEM_DESCRIPTION_MAX_LENGTH = 180;
export const BUDGET_PAYMENT_METHOD_MAX_LENGTH = 80;
export const BUDGET_EVENT_LOCATION_MAX_LENGTH = 180;
export const BUDGET_EVENT_MAX_DAYS = 10;
export const BUDGET_DURATION_HOURS_MAX = 24;
export const BUDGET_DEFAULT_VALIDITY_DAYS = 15;
export const BUDGET_ADVANCE_PERCENTAGE_STEP = 5;
