export type ActiveView =
  | "dashboard"
  | "leads"
  | "budgets"
  | "contracts"
  | "signatures"
  | "clients"
  | "employees"
  | "users"
  | "events"
  | "finances"
  | "debts"
  | "investments"
  | "profile"
  | "settings";
