export type ActiveView =
  | "dashboard"
  | "leads"
  | "budgets"
  | "contracts"
  | "signatures"
  | "payments"
  | "clients"
  | "employees"
  | "positions"
  | "supplies"
  | "users"
  | "events"
  | "publicIntake"
  | "profile";
